name: OpenAPI

on:
  push:
    paths:
      - 'rest-api/**'
#      - '.github/workflows/openapi.yml'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'rest-api/**'
#      - '.github/workflows/openapi.yml'

jobs:
  validate:
    name: Validate OpenAPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate
        uses: mbowman100/swagger-validator-action@master
        with:
          files: |
            ./rest-api/openapi.yaml
